[PDF]
qbroad = 0.055
qdamp =  0.05
[Measurement]
keV = 59.798
[R_val]
rmin = 1
rmax = 30
rstep = 0.01
[files]
cifs = './cifs/'
out = './results/'
[Verbose]
step = true
results = true

[Restraints]
delta2 = [0.0, 8.0, 1.0]
scale = [0.0, 10.0, 6.283]
adp = [0.0, 5.0]
lat = 0.5

[[param_order]]
free = ["lat"]
fix = []


[[param_order]]
free = ["delta2", "adp"]
fix = []

[[param_order]]
free = ["mag"]
fix = []